# Generated by Django 3.2.9 on 2021-12-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_follower', to='gallery.profile')),
                ('p_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_following', to='gallery.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='gallery.FollowSystem', to='gallery.Profile'),
        ),
    ]
