# Generated by Django 3.2.9 on 2021-12-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='author',
        ),
    ]
